title: Leon's Gallery
author: Leon Xu
email: leonxu798@gmail.com
description: My Photograph Collection

social:
  twitter:
  facebook:
  instagram:
  github:
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
