title: My Gallery
author: Leon Xu
email: leonxu624@gmx.com
description: Photography for myself.

social:
  twitter:
  facebook:
  instagram:
  github:
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
